In [1]:
pip install numpy


In [8]:
# USING NUMPY 

#QUESTION 1

import numpy as np
random_array = np.random.randint(10, 51, 20)
print(random_array)
mean_value = np.mean(random_array)
print(mean_value)
std_deviation = np.std(random_array)
print(std_deviation)

[24 46 13 46 40 40 49 34 30 45 48 30 19 19 31 47 40 33 28 35]
34.85
10.398437382607062


In [27]:
#QUESTION 2

import numpy as np
random_2d_array = np.random.rand(6, 5)
reshaped_array = random_2d_array.reshape(5, 6)
print("Original (6,5) Array:\n", random_2d_array)
print("\nReshaped (5,6) Array:\n", reshaped_array)

Original (6,5) Array:
 [[0.09293076 0.37593902 0.73829956 0.1850013  0.81221878]
 [0.35321686 0.14475994 0.4766139  0.55086057 0.50242399]
 [0.76672444 0.87636388 0.60990105 0.90678729 0.0870977 ]
 [0.78887162 0.78100021 0.62670176 0.51237598 0.01654144]
 [0.87729333 0.05665481 0.82787716 0.09786031 0.4599591 ]
 [0.76819497 0.29493432 0.16904769 0.24305849 0.31923958]]

Reshaped (5,6) Array:
 [[0.09293076 0.37593902 0.73829956 0.1850013  0.81221878 0.35321686]
 [0.14475994 0.4766139  0.55086057 0.50242399 0.76672444 0.87636388]
 [0.60990105 0.90678729 0.0870977  0.78887162 0.78100021 0.62670176]
 [0.51237598 0.01654144 0.87729333 0.05665481 0.82787716 0.09786031]
 [0.4599591  0.76819497 0.29493432 0.16904769 0.24305849 0.31923958]]


In [42]:
#QUESTION 3

import numpy as np
array_5x5 = np.arange(1, 26).reshape(5, 5)
subarray = array_5x5[1:4, 0:3]
print("Original 5x5 Array:n", array_5x5)
print("Extracted Subarray:\n", subarray)

Original 5x5 Array:n [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Extracted Subarray:
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [9]:
#QUESTION 4

import numpy as np
A=np.random.randint(1,100,10)
B=np.random.randint(1,100,10)
ADD=A+B
MUL=ADD*2
print("\nA\n")
print (A)
print("\nB\n")
print(B)
print("\nADDITION\n")
print(ADD)
print("\nMULTIPLICATION\n")
print(MUL)


A

[67 28 21 65 39 68 66 52 32 90]

B

[64 46 52 25 77 80 75  8  7 66]

ADDITION

[131  74  73  90 116 148 141  60  39 156]

MULTIPLICATION

[262 148 146 180 232 296 282 120  78 312]


In [55]:
#QUESTION 5

import numpy as np
A = np.random.randint(1, 11, (3, 4))
B = np.array([1, 2, 3, 4])
C = A + B
print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nArray C:")
print(C)


Array A:
[[ 1  5  8  5]
 [ 1  2  3 10]
 [ 7  4  9  1]]

Array B:
[1 2 3 4]

Array C:
[[ 2  7 11  9]
 [ 2  4  6 14]
 [ 8  6 12  5]]


In [12]:
#QUESTION 6

import numpy as np
array_2A= np.random.randint(1,100,(3,3))
print("\nARRAY\n")
print(array_2A)
row_sums = np.sum(array_2A,axis=1)
max_row_index = np.argmax(row_sums)
max_value_in_row = np.max(array_2A[max_row_index])
print("\nROW SUMS\n")
print(row_sums)
print("\nROW INDEX\n")
print(max_row_index)
print("\nMAX VALUE\n")
print(max_value_in_row)



ARRAY

[[69  1 88]
 [12 76 68]
 [53 74 54]]

ROW SUMS

[158 156 181]

ROW INDEX

2

MAX VALUE

74


In [15]:
#QUESTION 7

import numpy as np
A= np.random.randint(1,10,(2,2))
B=np.random.randint(1,10,(2,2))
print("\nA\n")
print(A)
print("\nB\n")
print(B)
MUL=np.dot(A,B)
print("\nMUL\n")
print(MUL)


A

[[6 8]
 [6 6]]

B

[[1 9]
 [5 2]]

MUL

[[46 70]
 [36 66]]


In [17]:
#QUESTION 8

import numpy as np
A=np.random.randint(1,50,(6,6))
print("\nA\n")
print(A)
boolean_mask=A>25
print("\nBoolean\n")
print(boolean_mask)
A[A>25]


A

[[43 21 46 35 33 23]
 [44  1 28  4 42 28]
 [43 27 45 22 46  1]
 [49 44 26 15  8 23]
 [24 17 17 45 28 23]
 [17 43 45 30  7 42]]

Boolean

[[ True False  True  True  True False]
 [ True False  True False  True  True]
 [ True  True  True False  True False]
 [ True  True  True False False False]
 [False False False  True  True False]
 [False  True  True  True False  True]]


array([43, 46, 35, 33, 44, 28, 42, 28, 43, 27, 45, 46, 49, 44, 26, 45, 28,
       43, 45, 30, 42], dtype=int32)

In [22]:
#QUESTION 10

import numpy as np
A= np.random.randint(1,10,(3,3))
B= A-2
print("\nA\n",A)
print("\nB\n",B)
c= np.square(B)
print("\nC\n",c)
D= np.reciprocal(c.astype(float))
print("\nD\n",D)


A
 [[8 1 1]
 [4 7 3]
 [4 1 9]]

B
 [[ 6 -1 -1]
 [ 2  5  1]
 [ 2 -1  7]]

C
 [[36  1  1]
 [ 4 25  1]
 [ 4  1 49]]

D
 [[0.02777778 1.         1.        ]
 [0.25       0.04       1.        ]
 [0.25       1.         0.02040816]]


In [26]:
#QUESTION 9

import numpy as np
random_float = np.random.rand(6,6)
print("\nRANDOM FLOAT\n",random_float)
median_column= np.median(random_float,axis=0)
median_row= np.median(random_float,axis=1)
varience_column= np.var(random_float,axis=0)
varience_row= np.var(random_float,axis=1)
print("\nMEDIAN OF COLUMN \n",median_column)
print("\nMEDIAN OF ROW \n",median_row)
print("\nVARIENCE OF COLUMN \n", varience_column)
print("\nVARIENCE OF ROW \n",varience_row)



RANDOM FLOAT
 [[0.70161014 0.07113466 0.54609155 0.91393514 0.1160215  0.50399865]
 [0.59577604 0.76428343 0.64358606 0.34919943 0.67051248 0.67864665]
 [0.71642537 0.46985797 0.47316468 0.56812109 0.59560058 0.53743685]
 [0.73884302 0.46892197 0.6018153  0.7981278  0.02839622 0.94849829]
 [0.29945787 0.91660536 0.87408448 0.59787124 0.16700323 0.81540662]
 [0.38390274 0.13129359 0.39131791 0.38161461 0.97074607 0.1541845 ]]

MEDIAN OF COLUMN 
 [0.64869309 0.46938997 0.57395342 0.58299616 0.3813019  0.60804175]

MEDIAN OF ROW 
 [0.5250451  0.65704927 0.55277897 0.67032916 0.70663893 0.38275868]

VARIENCE OF COLUMN 
 [0.02928608 0.09331252 0.02312527 0.04156845 0.1177573  0.06427923]

VARIENCE OF ROW 
 [0.09031377 0.01687179 0.00699621 0.08730986 0.08312514 0.07650393]


In [121]:
pip install pandas

In [28]:
# PANDAS 

#QUESTION 1

import pandas as pd
df = pd.read_csv('auto-mpg.csv')
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [29]:
print("The first 10 rows of the dataset : ")
df.head(10)

The first 10 rows of the dataset : 


mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [30]:
print("Total no.of Rows and Colunms : ")
df.shape

Total no.of Rows and Colunms : 


(398, 9)

In [31]:
print("Summary Statics : ")
df.describe()

Summary Statics : 


mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [32]:
#QUESTION 2- PANDAS

df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [33]:
print("Filtered Data of Cars")
df[(df['model year'] == 75) & (df['weight'] < 3000)][['car name', 'weight', 'mpg']]

Filtered Data of Cars


car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [34]:
#QUESTION 3 - PANDAS 

print("Missing Value : ")
df.isnull().sum()

Missing Value : 


mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [38]:
hp = df[(df['horsepower']!= '?')]['horsepower'].astype(int).median()
hps = df['horsepower'].values
hps[hps=='?'] = hp
df['horsepower']= hps.astype(int)
df['horsepower']

0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: int64

In [39]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [40]:
#QUESTION 4- pandas
df["power_to_weight_ratio"]=df["horsepower"]/df["weight"]



In [41]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

In [42]:
#QUESTION 5- PANDAS

grouped_cars = df.groupby('origin')['mpg'].mean()
grouped_cars


origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [43]:
#QUESTION 6- PANDAS 

top_10_mpg = df.sort_values('mpg', ascending=False).head(10)
top_10_mpg
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']
df['performance_score'] = df.apply(performance_score, axis=1)
df.head()


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   

   performance_score  
0           0.061644  
1           0.046710  
2           0.057625  
3           0.055928  
4           0.051754

In [44]:
#QUESTION-7 - PANDAS 

def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   

   performance_score  
0           0.061644  
1           0.046710  
2           0.057625  
3           0.055928  
4           0.051754

In [45]:
#QUESTION 8 - PANDAS 

summary_df = df.groupby('model year').agg({'mpg': 'mean', 'weight': 'mean', 'horsepower': 'mean'})
summary_df


mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.535714
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.185185
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.551724
81          30.334483  2522.931034   81.448276
82          31.709677  2453.548387   81.838710

In [48]:
#QUESTION 9- PANDAS 


filtered_df = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]
filtered_df.to_csv('high_mpg_cars.csv', index=False)
print("Filtered data saved to high_mpg_cars.csv")

Filtered data saved to high_mpg_cars.csv


In [49]:
#QUESTION - 10 -PANDAS

Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['mpg'] < lower_bound) | (df['mpg'] > upper_bound)]
outlier_df = outliers[['car name', 'mpg', 'model year']]
outlier_df


car name   mpg  model year
322  mazda glc  46.6          80